# Generated by Django 4.2.6 on 2024-11-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lenguaje',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='lenguaje',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
