# Generated by Django 4.2.6 on 2024-11-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_lenguaje_descripcion_alter_lenguaje_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lenguaje',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
