# Generated by Django 4.2.6 on 2024-11-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_lenguaje_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('des', models.CharField(max_length=100)),
                ('git', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('link', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
        migrations.DeleteModel(
            name='Lenguaje',
        ),
    ]
