# Generated by Django 4.2.6 on 2024-11-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_proyectos_delete_lenguaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectos',
            name='des',
        ),
        migrations.AddField(
            model_name='proyectos',
            name='descripcion',
            field=models.CharField(default='Sin descripción', max_length=255),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='git',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
